#!/usr/bin/env python
import sys, subprocess
import time

def main(args):
    while True:
        time.sleep(10)
        subprocess.check_output(['./build'])

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
