#!/usr/bin/env python3
import sys, time
from pprint import pprint

from ant        import Ant
from states     import states
from update     import update
from display    import display
from parameters import parameters

def main(args):
    N = 100
    ants = [Ant('exploration', 'at-nest', 0, None, i) for i in range(N)]

    step = 0
    try:
        while True:
            stateCounts = {state : {substate : 0 for substate in stateDict} 
                           for state, stateDict in states.items()}
            ants = [update(states, parameters, ant) for ant in ants]
            for ant in ants:
                stateCounts[ant.state][ant.substate] += 1
            if step % 10 == 0:
                print(step)
                pprint(stateCounts)
            step += 1
            if step == 100:
                1/0

    except KeyboardInterrupt:
        print('Ran {} steps'.format(step))

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))

