#!/usr/bin/env python3
import sys
from pprint import pprint

from ant        import Ant
from states     import states
from update     import update
from parameters import parameters

def main(args):
    N = 1
    ants = [Ant('exploration', 'at-nest', 0, None, i) for i in range(N)]

    step = 0
    try:
        while True:
            for ant in ants:
                update(states, parameters, ant)
            step += 1
            print(str(step) + '\r', end='')
    except KeyboardInterrupt:
        print('Ran {} steps'.format(step))

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))

