#!/usr/bin/env python3
import sys, time
from pprint import pprint

from ant        import Ant
from states     import states
from update     import update
from display    import display
from parameters import parameters

def main(args):
    N = 1
    ants = [Ant('exploration', 'at-nest', 0, None, i) for i in range(N)]

    step = 0
    try:
        while True:
            ants = [update(states, parameters, ant) for ant in ants]
            display(ants)
            print(step)
            step += 1

    except KeyboardInterrupt:
        print('Ran {} steps'.format(step))

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))

